print("Hola mundo!")
print('Hola "Vikingo".')
print(100+50)
print("Me llamo \"Frank\".")
print("Esta es una línea \nY esta es otra línea")
print('This isn\'t a number')
print("Línea 1\nLínea 2\nLínea 3")
print(" A\tB\tC\n D\tE\tF\n G\tH\tI\n")
print("Barra Normal: /\nBarra Invertida: \\")